### Getting Agent information

GET http://localhost:8080

### Detect Intent (no formatting)

POST http://localhost:8080
Content-Type: application/json

{
    "q": "Hi",
    "session_id": "test",
    "lang": "en"
}

### Detect Intent (with formatting)

POST http://localhost:8080?format=true
Content-Type: application/json

{
    "q": "Hi",
    "session_id": "test",
    "lang": "en"
}